
-- Tabelle

CREATE TABLE cliente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50)
	cognome VARCHAR(50)
	username VARCHAR(50),
    password VARCHAR(50),
    saldo DOUBLE
);

CREATE TABLE venditore (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50)
	cognome VARCHAR(50)
	username VARCHAR(50),
    password VARCHAR(50),
    saldo DOUBLE
);

CREATE TABLE oggetti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(64),
    immagine VARCHAR(256),
    descrizione VARCHAR(4096),
    quantita INTEGER,
    prezzo DOUBLE,
    idVenditore INTEGER,
    FOREIGN KEY (idVenditore) REFERENCES venditore(id)
);

-- Popolamento



INSERT INTO cliente(id, nome, cognome, username, password, saldo)
VALUES  (default, 'Silvio', 'Berlusconi','ricco', '1', 1000.00),
        (default, 'Marco', 'Tocco', 'povero', '1', 1.00);


INSERT INTO venditore(id, nome, cognome, username, password, saldo)
VALUES  (default, 'Jeff', 'Bezos','amazon', '1', 1000.00),
        (default, 'Marco', 'Tocco', 'povero', '1', 1.00);


INSERT INTO oggetti(id, nome, immagine, descrizione, quantita, prezzo, idvenditore)
VALUES	(default, 'The Brighton Beard Company: Black Pepper & Grapefruit', 'img/olio/bbc_olio.png', 'blank', 10 , 27.00 , 2),
		(default, 'Mr. Bear: Wilderness', 'img/olio/bear_olio.png', 'blank', 10 , 15.50 , 2),
		(default, 'Captain Fawcett''s: Beard Oil Private Stock', 'img/olio/capfaw_olio.png', 'blank', 15 , 49.00 , 2),
		(default, 'Morgan''s Beard Oil', 'img/olio/morgans_olio.png', 'blank', 17 , 20.90 , 2),
		(default, 'Mr. Natty: Sunshine Beard Elixir', 'img/olio/natty_olio.png', 'blank', 19 , 14.00 , 2);
        
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		